.Dd 2023-10-25
.Dt BMP2FF 1
.Os farbfeld-utils
.Sh NAME
.Nm bmp2ff
.Nd convert BMP (bitmap) image to farbfeld
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
reads a BMP image from stdin, converts it to
.Xr farbfeld 5
and writes the result to stdout.
.Pp
BMP is a raster graphics image format capable of storing two-dimensional
digital images in varous colour depths.
.br
There is currently no support for BMP images with RLE (Run Length Encoding)
compression.
.Pp
In case of an error
.Nm
writes a diagnostic message to stderr.
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
Image processed successfully.
.It 1
An error occurred.
.El
.Sh OPTIONS
The program takes no arguments.
.Sh EXAMPLES
$
.Nm
< image.bmp > image.ff
.Pp
$
.Nm
< image.bmp | bzip2 > image.ff.bz2
.Sh SEE ALSO
.Xr 2ff 1 ,
.Xr bzip2 1 ,
.Xr farbfeld 5 ,
.Xr farbfeld-utils 7
