.Dd 2024-03-29
.Dt FAX2FF 1
.Os farbfeld-utils
.Sh NAME
.Nm fax2ff.ps
.Nd converts Group 3 or 4 fax format to farbfeld
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
reads Group 3 or 4 fax format from stdin, converts it to
.Xr farbfeld 5
and writes the result to stdout.

Unlike other farbfeld programs this is written in PostScript and require an interpreter to use.
.Pp
In case of an error
.Nm
writes a diagnostic message to stderr.
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
Image processed successfully.
.It 1
An error occurred.
.El
.Sh OPTIONS
Each argument consists of the name and then equal sign and then the value.

Values can either be integers, or they can be the word "true" or "false" for boolean parameters.

The possible parameters are:
.Bl -tag -width Ds
.It BlackIs1
If true, results in reverse video; the default is false, meaning not reverse video.
.It Columns
The width of the image. The default value is 1728.
.It DamagedRowsBeforeError
Indicates how many bad scanlines are tolerated before it will terminate with an error. Requires
EndOfLine to also be set. Tolerating bad scanlines may be helpful to recover a damaged fax message.
The default value is zero.
.It EncodedByteAlign
If true, specifies to read or write extra bits at the end of each scanline so that each scanline
begins at a byte boundary. If false (the default) then it does not do this.
.It EndOfBlock
If true (the default), then it will automatically add a end-of-block mark at the end when encoding,
and expects such a mark when decoding. If false, then it doesn't use a end-of-block mark.
.It EndOfLine
If true, emits or requires a end-of-line pattern. If false (default), then it doesn't.
.It K
Type of encoding scheme. If zero (the default), then it uses Modified Huffman format. If positive,
then it uses Modified READ, where the number specifies the maximum number of scanlines that are
allowed to be encoded by a single Modified READ block. If negative, then it uses Modified Modified
READ (Group 4).
.It Rows
The height of the image. The default value is 100.
.El
.Sh EXAMPLES
$
.Nm
< fax.format > image.ff
.Sh SEE ALSO
.Xr ff2fax 1 ,
.Xr farbfeld 5 ,
.Xr farbfeld-utils 7
