.Dd 2024-03-22
.Dt FF2MORSE 1
.Os farbfeld-utils
.Sh NAME
.Nm ff2morse
.Nd convert farbfeld to a file format used in one episode of Murdoch Mysteries television show
.Sh SYNOPSIS
.Nm
.Op palette
.Sh DESCRIPTION
.Nm
reads a
.Xr farbfeld 5
image from stdin, converts it to the bespoke morse format and writes the result to
stdout.
.Pp
This program implements a file format used in one episode of Murdoch Mysteries
television show. Each line has letters/numbers which are converted into morse
code and then the dots and dashes are converted to pixels (ignoring the breaks
between letters); each line of text is a new scanline of the picture. (Only
letters and numbers can be used; punctuations, accented alphabets, etc are not
possible).

The program takes one optional argument being any combination of the following
letters:

   c: Encodes using a compact format (everything on one line, starting with
      the width number inside of <>).
   r: Reverse video. If specified, then a dot is white and a dash is black.
      Normally (if not specified), then a dot is black and a dash is white.
.Pp
In case of an error
.Nm
writes a diagnostic message to stderr.
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
Image processed successfully.
.It 1
An error occurred.
.El
.Sh EXAMPLES
$
.Nm
cr < image.ff
.Pp
$
.Nm
r < image.ff > morse.txt
.Sh SEE ALSO
.Xr morse2ff 1 ,
.Xr farbfeld 5
