.Dd 2023-11-10
.Dt FF2XBM 1
.Os farbfeld-utils
.Sh NAME
.Nm ff2xbm
.Nd convert farbfeld to X BitMap (XBM) image
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
reads an X BitMap (XBM) image from stdin, converts it to
.Xr farbfeld 5
and writes the result to stdout.

XBM is a file format for bi-level raster images, originally associated with
the X Window System. It was, and to some extent still is, widely supported by
graphics software.

An XBM file is plain text, and doubles as a fragment of C programming code.
The format is very inefficient in size, but it can be useful as a simple way
to embed an image into a C program.

This encoder takes zero, one or three arguments, as follows:
   Picture name (the default is "picture")
   X hot point
   Y hot point

Only the high bit of the red channel of input is used, where black means
foreground and white means background. To do something else, use ff-swizzle
and/or other programs at first.
.Pp
In case of an error
.Nm
writes a diagnostic message to stderr.
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
Image processed successfully.
.It 1
An error occurred.
.El
.Sh EXAMPLES
$
.Nm
< image.xbm > image.ff
.Pp
$
.Nm
< image.xbm | bzip2 > image.ff.bz2
.Sh SEE ALSO
.Xr bzip2 1 ,
.Xr xbm2ff 1,
.Xr farbfeld 5 ,
.Xr farbfeld-utils 7
